import { useState, useEffect, useCallback, useMemo } from 'react'
import {
  fetchHelloAssoMembers, fetchHelloAssoDonations,
  sendBrevoCampaign, sendTelegramMessage,
  fetchGitHubCommits, fetchNotionDatabase, checkPageLink,
  saveLocal, loadLocal, parseCSV, exportCSV,
} from './api'

const C={bg:'#f6f4ef',bgAlt:'#edeae3',white:'#fff',navy:'#1a2744',navyLight:'#2d3f5e',navyFade:'#1a274412',sky:'#4a90d9',skyFade:'#4a90d915',terra:'#c45a3c',ochre:'#d4a843',green:'#3a9d6a',greenFade:'#3a9d6a12',greenBg:'#e8f5ee',red:'#d94452',redBg:'#fdeaec',muted:'#8494a7',mutedLight:'#a8b5c4',border:'#e5e1d8',borderLight:'#eeebe4',tGreen:'#e8f5ee',tOchre:'#fff4e6',tSky:'#e8f0fb',tRed:'#fdeaec',tTerra:'#fce8e3',tNavy:'#e3e8f0',tPurple:'#ede9fe'}
const SITE='https://institut-rousseau-kb9p.vercel.app'
const PAGES=[{path:'/',name:'Accueil',group:'Principal'},{path:'/publications.html',name:'Publications',group:'Principal'},{path:'/auteurs.html',name:'Auteurs',group:'Principal'},{path:'/evenements.html',name:'Événements',group:'Principal'},{path:'/presse.html',name:'Presse',group:'Principal'},{path:'/road-to-net-zero.html',name:'Road to Net Zero',group:'Principal'},{path:'/le-projet.html',name:'Le projet',group:'Principal'},{path:'/contact.html',name:'Contact',group:'Principal'},{path:'/don.html',name:'Faire un don',group:'Engagement'},{path:'/adhesion.html',name:'Adhésion',group:'Engagement'},{path:'/confidentialite.html',name:'Confidentialité',group:'Engagement'},{path:'/thematique-ecologie.html',name:'Écologie',group:'Pôles'},{path:'/thematique-economie.html',name:'Économie',group:'Pôles'},{path:'/thematique-institutions.html',name:'Institutions',group:'Pôles'},{path:'/thematique-social.html',name:'Social',group:'Pôles'},{path:'/thematique-international.html',name:'International',group:'Pôles'},{path:'/thematique-culture.html',name:'Culture',group:'Pôles'}]
const TAGS=[{id:'membre',label:'Membre',color:C.green,bg:C.tGreen,icon:'👤'},{id:'donateur',label:'Donateur',color:C.ochre,bg:C.tOchre,icon:'💛'},{id:'newsletter',label:'Newsletter',color:C.sky,bg:C.tSky,icon:'📬'},{id:'presse',label:'Presse',color:C.terra,bg:C.tTerra,icon:'📰'},{id:'auteur',label:'Auteur',color:C.navy,bg:C.tNavy,icon:'✍️'},{id:'evenement',label:'Événement',color:'#8b5cf6',bg:C.tPurple,icon:'🎤'}]
const AUTO=[{id:'welcome_member',name:'Bienvenue membre',trigger:"Nouveau tag 'membre'",channel:'email',desc:'Accueil + lien Telegram + invitation newsletter',active:true},{id:'welcome_donor',name:'Merci donateur',trigger:"Nouveau tag 'donateur'",channel:'email',desc:'Reçu fiscal + incitation adhésion',active:true},{id:'welcome_nl',name:'Bienvenue newsletter',trigger:'Inscription newsletter',channel:'email',desc:'Présentation + derniers articles + nudge adhésion',active:true},{id:'nudge_adhesion',name:'Relance adhésion',trigger:'NL > 30j sans tag membre',channel:'email',desc:'Suggestion adhésion abonnés NL non-membres',active:false},{id:'new_article_tg',name:'Alerte article',trigger:'Article publié Notion',channel:'telegram',desc:'Broadcast Telegram automatique',active:true},{id:'event_reminder',name:'Rappel événement',trigger:'J-3 événement',channel:'email+telegram',desc:'Rappel inscrits + Telegram',active:false}]
const TPL=[{label:'📬 Nouvel article',subject:'Nouvelle publication — Institut Rousseau',body:`📝 Nouveau\n\n[TITRE]\nPar [AUTEUR]\n\n[Résumé]\n\n🔗 ${SITE}/publications.html\n\n—\nInstitut Rousseau`},{label:'🎤 Événement',subject:'Invitation — [NOM]',body:`🗓️ [NOM]\n📍 [LIEU] — [DATE]\n\nInscription : ${SITE}/evenements.html`},{label:'💛 Dons',subject:"Soutenez un labo d'idées indépendant",body:`100% indépendant. 66% déductible.\n\n👉 ${SITE}/don.html`},{label:'🫶 Adhésion',subject:"Rejoignez l'Institut",body:`À partir de 10€/an.\n\n👉 ${SITE}/adhesion.html`}]

const Ico=({d,size=16,color})=><svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color||'currentColor'} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d={d}/></svg>
const IC={home:'M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z',users:'M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2M9 3a4 4 0 100 8 4 4 0 000-8zM23 21v-2a4 4 0 00-3-3.87M16 3.13a4 4 0 010 7.75',file:'M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8zM14 2v6h6M16 13H8M16 17H8',link:'M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71',settings:'M12 15a3 3 0 100-6 3 3 0 000 6z',check:'M20 6L9 17l-5-5',x:'M18 6L6 18M6 6l12 12',plus:'M12 5v14M5 12h14',ext:'M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6M15 3h6v6M10 14L21 3',git:'M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 00-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0020 4.77 5.07 5.07 0 0019.91 1S18.73.65 16 2.48a13.38 13.38 0 00-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 005 4.77a5.44 5.44 0 00-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 009 18.13V22',trash:'M3 6h18M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2',search:'M11 3a8 8 0 100 16 8 8 0 000-16zM21 21l-4.35-4.35',alert:'M12 2L2 22h20L12 2zM12 9v4M12 17h.01',save:'M19 21H5a2 2 0 01-2-2V5a2 2 0 012-2h11l5 5v11a2 2 0 01-2 2zM17 21v-8H7v8M7 3v5h8',refresh:'M23 4v6h-6M1 20v-6h6M3.51 9a9 9 0 0114.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0020.49 15',play:'M5 3l14 9-14 9V3z',download:'M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3',upload:'M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M17 8l-5-5-5 5M12 3v12',mail:'M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2zM22 6l-10 7L2 6',send:'M22 2L11 13M22 2l-7 20-4-9-9-4 20-7z',zap:'M13 2L3 14h9l-1 10 10-12h-9l1-10z',globe:'M12 2a10 10 0 100 20 10 10 0 000-20zM2 12h20'}

const Dot=({ok,label})=><span style={{display:'inline-flex',alignItems:'center',gap:5,fontSize:11,fontWeight:600,color:ok?C.green:C.muted}}><span style={{width:7,height:7,borderRadius:'50%',background:ok?C.green:C.border,boxShadow:ok?`0 0 6px ${C.green}60`:'none'}}/>{label}</span>
const Badge=({s,label,color:c2,bg:b2})=>{const m={ok:{c:C.green,bg:C.tGreen,l:'OK'},error:{c:C.red,bg:C.redBg,l:'Erreur'},checking:{c:C.sky,bg:C.tSky,l:'…'},unchecked:{c:C.muted,bg:C.bgAlt,l:'—'},published:{c:C.green,bg:C.tGreen,l:'Publié'},draft:{c:C.muted,bg:C.bgAlt,l:'Brouillon'},ready:{c:C.sky,bg:C.tSky,l:'Prêt'}};const p=m[s]||{};return<span style={{padding:'2px 10px',borderRadius:20,fontSize:11,fontWeight:600,color:c2||p.c||C.muted,background:b2||p.bg||C.bgAlt,whiteSpace:'nowrap'}}>{label||p.l||s}</span>}
const CTag=({tagId,small})=>{const t=TAGS.find(x=>x.id===tagId);if(!t)return null;return<span style={{padding:small?'0 6px':'1px 8px',borderRadius:12,fontSize:small?9:10,fontWeight:600,color:t.color,background:t.bg}}>{t.icon} {t.label}</span>}
const Btn=({children,onClick,v='primary',sm,disabled,style:sx,title})=>{const s={primary:{background:C.navy,color:C.white,border:'none'},sky:{background:C.sky,color:C.white,border:'none'},green:{background:C.green,color:C.white,border:'none'},danger:{background:C.red,color:C.white,border:'none'},ghost:{background:'transparent',color:C.navy,border:`1px solid ${C.border}`},ochre:{background:C.ochre,color:C.white,border:'none'},soft:{background:C.navyFade,color:C.navy,border:'none'}};return<button onClick={onClick} disabled={disabled} title={title} style={{borderRadius:8,cursor:disabled?'not-allowed':'pointer',fontWeight:600,fontSize:sm?11:13,display:'inline-flex',alignItems:'center',gap:5,padding:sm?'5px 10px':'9px 18px',opacity:disabled?.5:1,transition:'all .15s',fontFamily:'inherit',...s[v],...sx}}>{children}</button>}
const Metric=({icon,label,val,sub,color=C.sky,onClick})=><div onClick={onClick} style={{background:C.white,borderRadius:14,padding:'18px 20px',border:`1px solid ${C.border}`,flex:'1 1 150px',minWidth:130,cursor:onClick?'pointer':'default'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:6}}><span style={{color:C.muted,fontSize:11,fontWeight:600,textTransform:'uppercase',letterSpacing:'.04em'}}>{label}</span><span style={{color,opacity:.4}}><Ico d={icon} size={15}/></span></div><div style={{fontSize:28,fontWeight:700,color:C.navy,fontFamily:"'Cormorant Garamond',Georgia,serif",letterSpacing:'-.02em'}}>{val}</div>{sub&&<div style={{fontSize:11,color:C.muted,marginTop:2}}>{sub}</div>}</div>
const Card=({children,style:sx,padding:p})=><div style={{background:C.white,borderRadius:14,padding:p||20,border:`1px solid ${C.border}`,...sx}}>{children}</div>
const STitle=({icon,children,right,sub})=><div style={{marginBottom:18}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{display:'flex',alignItems:'center',gap:8}}>{icon&&<span style={{color:C.sky}}><Ico d={icon} size={20}/></span>}<h2 style={{fontSize:20,fontWeight:700,margin:0,fontFamily:"'Cormorant Garamond',Georgia,serif",color:C.navy}}>{children}</h2></div>{right}</div>{sub&&<p style={{fontSize:12,color:C.muted,margin:'4px 0 0 28px'}}>{sub}</p>}</div>
const Field=({label,children,help})=><div style={{marginBottom:14}}><label style={{display:'block',fontSize:11,fontWeight:700,color:C.navy,marginBottom:4,letterSpacing:'.02em'}}>{label}</label>{children}{help&&<div style={{fontSize:10,color:C.mutedLight,marginTop:3}}>{help}</div>}</div>
const iStyle={width:'100%',padding:'9px 12px',borderRadius:8,border:`1px solid ${C.border}`,fontSize:13,outline:'none',boxSizing:'border-box',fontFamily:'inherit'}
const Modal=({open,onClose,title,children,wide})=>{if(!open)return null;return<div onClick={onClose} style={{position:'fixed',inset:0,background:'rgba(15,26,46,.45)',zIndex:1000,display:'flex',alignItems:'center',justifyContent:'center',backdropFilter:'blur(4px)'}}><div onClick={e=>e.stopPropagation()} style={{background:C.white,borderRadius:16,padding:'26px 30px',maxWidth:wide?680:500,width:'92%',boxShadow:'0 20px 60px rgba(15,26,46,.18)',maxHeight:'88vh',overflowY:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:20}}><h3 style={{margin:0,fontSize:18,color:C.navy,fontFamily:"'Cormorant Garamond',Georgia,serif"}}>{title}</h3><button onClick={onClose} style={{background:'none',border:'none',cursor:'pointer',color:C.muted,padding:4}}><Ico d={IC.x} size={18}/></button></div>{children}</div></div>}
const Td=({children,style:sx})=><td style={{padding:'10px 14px',borderBottom:`1px solid ${C.borderLight}`,...sx}}>{children}</td>

export default function App(){
  const[tab,setTab]=useState('overview')
  const[toast,setToast]=useState(null)
  const[config,setConfig]=useState(()=>loadLocal('config',{notionKey:'',notionDbId:'',ghOwner:'',ghRepo:'',ghToken:'',brevoKey:'',helloassoClientId:'',helloassoClientSecret:'',helloassoOrg:'',telegramBotToken:'',telegramChatId:''}))
  const[contacts,setContacts]=useState(()=>loadLocal('contacts',[]))
  const[notionArticles,setNotionArticles]=useState([])
  const[ghCommits,setGhCommits]=useState([])
  const[linkResults,setLinkResults]=useState(PAGES.map(p=>({...p,status:'unchecked',time:null})))
  const[automations,setAutomations]=useState(AUTO)
  const[activity,setActivity]=useState(()=>loadLocal('activity',[]))
  const[contactSearch,setContactSearch]=useState('')
  const[contactFilter,setContactFilter]=useState('all')
  const[contactTab,setContactTab]=useState('list')
  const[showAdd,setShowAdd]=useState(false)
  const[showImport,setShowImport]=useState(false)
  const[showDetail,setShowDetail]=useState(null)
  const[newC,setNewC]=useState({name:'',email:'',tags:['newsletter'],source:'manual'})
  const[importText,setImportText]=useState('')
  const[campaign,setCampaign]=useState({subject:'',body:'',targetTag:'newsletter',channel:'email'})
  const[notionLoading,setNotionLoading]=useState(false)
  const[notionError,setNotionError]=useState(null)
  const[ghLoading,setGhLoading]=useState(false)
  const[linkChecking,setLinkChecking]=useState(false)
  const[haLoading,setHaLoading]=useState(false)

  const notify=useCallback((msg,bad)=>{setToast({msg,bad});setTimeout(()=>setToast(null),3000)},[])
  const log=useCallback(msg=>{const e={msg,time:new Date().toISOString()};setActivity(p=>{const u=[e,...p].slice(0,50);saveLocal('activity',u);return u})},[])
  const saveC=l=>{setContacts(l);saveLocal('contacts',l)}
  const saveCfg=c=>{setConfig(c);saveLocal('config',c);notify('Sauvegardé')}

  const ghOk=!!(config.ghOwner&&config.ghRepo),notionOk=!!(config.notionKey&&config.notionDbId),brevoOk=!!config.brevoKey,haOk=!!(config.helloassoClientId&&config.helloassoClientSecret&&config.helloassoOrg),tgOk=!!(config.telegramBotToken&&config.telegramChatId)
  const services=[{name:'HelloAsso',ok:haOk},{name:'Brevo',ok:brevoOk},{name:'Telegram',ok:tgOk},{name:'Notion',ok:notionOk},{name:'GitHub',ok:ghOk}]
  const cc=services.filter(s=>s.ok).length
  const ct=id=>contacts.filter(c=>c.tags.includes(id)).length
  const okP=linkResults.filter(r=>r.status==='ok').length,errP=linkResults.filter(r=>r.status==='error').length
  const filt=useMemo(()=>contacts.filter(c=>(contactFilter==='all'||c.tags.includes(contactFilter))&&(!contactSearch||c.name.toLowerCase().includes(contactSearch.toLowerCase())||c.email.toLowerCase().includes(contactSearch.toLowerCase()))),[contacts,contactFilter,contactSearch])
  const pGroups=useMemo(()=>{const g={};PAGES.forEach(p=>{(g[p.group]=g[p.group]||[]).push(p)});return g},[])

  const syncHA=async()=>{if(!haOk){notify('Config HelloAsso incomplète',true);return};setHaLoading(true);try{const[m,d]=await Promise.all([fetchHelloAssoMembers(config.helloassoClientId,config.helloassoClientSecret,config.helloassoOrg),fetchHelloAssoDonations(config.helloassoClientId,config.helloassoClientSecret,config.helloassoOrg)]);let a=0;const u=[...contacts];[...m,...d].forEach(ha=>{if(!ha.email)return;const ex=u.find(c=>c.email.toLowerCase()===ha.email.toLowerCase());if(ex){if(!ex.tags.includes(ha.type)){ex.tags.push(ha.type);a++};if(ha.amount)ex.amount=(ex.amount||0)+ha.amount;ex.helloassoId=ha.helloassoId}else{u.push({id:Date.now()+a,name:ha.name,email:ha.email,tags:[ha.type,'newsletter'],source:'helloasso',date:ha.date,helloassoId:ha.helloassoId,amount:ha.amount});a++}});saveC(u);log(`HelloAsso: ${a} contacts`);notify(`HelloAsso: ${a} contacts`)}catch(e){notify('HelloAsso: '+e.message,true)};setHaLoading(false)}
  const doSend=async()=>{const t=contacts.filter(c=>c.tags.includes(campaign.targetTag)&&c.email);if(!t.length){notify('0 destinataire',true);return};if(campaign.channel==='telegram'){if(!tgOk){notify('Telegram non configuré',true);return};try{await sendTelegramMessage(config.telegramBotToken,config.telegramChatId,campaign.body);log('Telegram envoyé');notify('Telegram ✓')}catch(e){notify(e.message,true)}}else{if(!brevoOk){notify('Brevo non configuré',true);return};try{const r=await sendBrevoCampaign(config.brevoKey,{emails:t.map(c=>c.email),subject:campaign.subject,htmlContent:`<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px"><p>${campaign.body.replace(/\n/g,'<br>')}</p></div>`});log(`Brevo: ${r.sent} emails`);notify(`${r.sent} emails ✓`)}catch(e){notify(e.message,true)}}}
  const doGH=async()=>{if(!ghOk)return;setGhLoading(true);try{setGhCommits(await fetchGitHubCommits(config.ghOwner,config.ghRepo,config.ghToken))}catch(e){notify('GitHub: '+e.message,true)};setGhLoading(false)}
  const doNotion=async()=>{if(!notionOk)return;setNotionLoading(true);setNotionError(null);try{const a=await fetchNotionDatabase(config.notionKey,config.notionDbId);setNotionArticles(a);log(`Notion: ${a.length} articles`);notify(`${a.length} articles`)}catch(e){setNotionError(e.message)};setNotionLoading(false)}
  const doLinks=async()=>{setLinkChecking(true);const res=PAGES.map(p=>({...p,status:'unchecked',time:null}));for(let i=0;i<PAGES.length;i++){res[i]={...res[i],status:'checking'};setLinkResults([...res]);const r=await checkPageLink(`${SITE}${PAGES[i].path}`);res[i]={...res[i],...r};setLinkResults([...res])};setLinkChecking(false);const errs=res.filter(r=>r.status==='error').length;log(`Links: ${res.length-errs}/${res.length} OK`);notify(errs?`${errs} erreur(s)`:'Tout OK ✓',errs>0)}
  useEffect(()=>{if(ghOk)doGH()},[])

  const addContact=()=>{if(!newC.email)return;if(contacts.find(c=>c.email.toLowerCase()===newC.email.toLowerCase())){notify('Existant',true);return};saveC([{id:Date.now(),...newC,date:new Date().toISOString().slice(0,10)},...contacts]);log(`+${newC.name||newC.email}`);setNewC({name:'',email:'',tags:['newsletter'],source:'manual'});setShowAdd(false);notify('Ajouté')}
  const toggleTag=(id,tagId)=>saveC(contacts.map(c=>c.id!==id?c:{...c,tags:c.tags.includes(tagId)?c.tags.filter(t=>t!==tagId):[...c.tags,tagId]}))
  const delContact=id=>{saveC(contacts.filter(c=>c.id!==id));notify('Supprimé')}
  const doImport=()=>{const rows=parseCSV(importText);if(!rows.length){notify('Aucune donnée',true);return};let a=0;const u=[...contacts];rows.forEach(r=>{const email=(r.email||r.mail||r['e-mail']||'').toLowerCase().trim();if(!email||u.find(c=>c.email===email))return;const name=r.nom||r.name||r['nom complet']||`${r.prenom||''} ${r.nom||''}`.trim()||email.split('@')[0];const tags=(r.tags||r.tag||r.type||'newsletter').toLowerCase().split(/[;,]/).map(t=>t.trim()).filter(Boolean);u.push({id:Date.now()+a,name,email,tags,source:'import',date:new Date().toISOString().slice(0,10)});a++});saveC(u);log(`Import: ${a}`);setShowImport(false);setImportText('');notify(`${a} importé(s)`)}

  const NAV=[{id:'overview',label:"Vue d'ensemble",icon:IC.home},{id:'contacts',label:'Contacts',icon:IC.users},{id:'articles',label:'Articles',icon:IC.file},{id:'site',label:'Site',icon:IC.link},{id:'config',label:'Config',icon:IC.settings}]

  return(<div style={{minHeight:'100vh',background:C.bg,fontFamily:"'Source Sans 3','Segoe UI',sans-serif",color:C.navy}}>
    {toast&&<div style={{position:'fixed',top:16,right:16,zIndex:2000,padding:'11px 22px',borderRadius:10,fontSize:13,fontWeight:600,color:C.white,background:toast.bad?C.red:C.green,boxShadow:'0 8px 30px rgba(0,0,0,.15)',animation:'slideIn .3s ease'}}>{toast.msg}</div>}

    <header style={{background:C.navy,height:56,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 24px',borderBottom:`3px solid ${C.sky}`}}>
      <div style={{display:'flex',alignItems:'center',gap:12}}><div style={{width:32,height:32,borderRadius:9,background:`linear-gradient(135deg,${C.sky},${C.terra})`,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:800,fontSize:14,color:C.white,fontFamily:"'Cormorant Garamond',Georgia,serif"}}>IR</div><div><div style={{color:C.white,fontSize:15,fontWeight:700,fontFamily:"'Cormorant Garamond',Georgia,serif",lineHeight:1.1}}>Institut Rousseau</div><div style={{color:C.white,opacity:.35,fontSize:10,fontWeight:500,letterSpacing:'.06em',textTransform:'uppercase'}}>Back-office</div></div></div>
      <div style={{display:'flex',gap:12,alignItems:'center'}}><div style={{display:'flex',gap:6}}>{services.map(s=><span key={s.name} title={`${s.name}: ${s.ok?'OK':'—'}`} style={{width:8,height:8,borderRadius:'50%',background:s.ok?C.green:C.muted+'40',cursor:'pointer'}} onClick={()=>setTab('config')}/>)}</div><a href={SITE} target="_blank" rel="noopener" style={{color:C.white,opacity:.5,fontSize:11,textDecoration:'none',display:'flex',alignItems:'center',gap:4}}><Ico d={IC.ext} size={12}/> Site</a>{ghOk&&<a href={`https://github.com/${config.ghOwner}/${config.ghRepo}`} target="_blank" rel="noopener" style={{color:C.white,opacity:.5,fontSize:11,textDecoration:'none'}}><Ico d={IC.git} size={12}/></a>}</div>
    </header>

    <nav style={{background:C.white,borderBottom:`1px solid ${C.border}`,display:'flex',padding:'0 24px',overflowX:'auto',gap:2}}>{NAV.map(t=><button key={t.id} onClick={()=>setTab(t.id)} style={{padding:'13px 18px',border:'none',background:'none',cursor:'pointer',fontSize:13,fontWeight:600,display:'flex',alignItems:'center',gap:6,color:tab===t.id?C.navy:C.muted,fontFamily:'inherit',borderBottom:tab===t.id?`2px solid ${C.sky}`:'2px solid transparent'}}><Ico d={t.icon}/>{t.label}</button>)}</nav>

    <main style={{maxWidth:1120,margin:'0 auto',padding:'24px 20px'}}>

    {/* OVERVIEW */}
    {tab==='overview'&&<>{cc<3&&<div style={{background:`linear-gradient(135deg,${C.navy},${C.navyLight})`,borderRadius:14,padding:'20px 24px',marginBottom:20,color:C.white}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:15,fontWeight:700,marginBottom:4}}>Configuration</div><div style={{fontSize:12,opacity:.7}}>{cc}/5 services — {services.filter(s=>!s.ok).map(s=>s.name).join(', ')}</div></div><Btn v="sky" sm onClick={()=>setTab('config')}>Configurer</Btn></div><div style={{display:'flex',gap:8,marginTop:14}}>{services.map(s=><div key={s.name} style={{display:'flex',alignItems:'center',gap:5,padding:'4px 10px',borderRadius:6,background:s.ok?'rgba(58,157,106,.2)':'rgba(255,255,255,.1)',fontSize:11}}><span style={{width:6,height:6,borderRadius:'50%',background:s.ok?C.green:'rgba(255,255,255,.3)'}}/>{s.name}</div>)}</div></div>}
      <div style={{display:'flex',flexWrap:'wrap',gap:12,marginBottom:22}}><Metric icon={IC.users} label="Contacts" val={contacts.length} sub={`${ct('membre')} membres · ${ct('donateur')} donateurs`} color={C.navy} onClick={()=>setTab('contacts')}/><Metric icon={IC.mail} label="Newsletter" val={ct('newsletter')} sub={brevoOk?'Brevo':'—'} color={C.sky} onClick={()=>{setTab('contacts');setContactFilter('newsletter')}}/><Metric icon={IC.file} label="Articles" val={notionArticles.length||'—'} sub={notionOk?'Notion':'—'} color={notionOk?C.green:C.muted} onClick={()=>setTab('articles')}/><Metric icon={IC.globe} label="Pages" val={`${okP}/${PAGES.length}`} sub={errP?`${errP} err`:okP?'OK':'—'} color={errP?C.red:okP?C.green:C.muted} onClick={()=>setTab('site')}/></div>
      <Card style={{marginBottom:16}}><h3 style={{fontSize:13,fontWeight:700,margin:'0 0 12px',textTransform:'uppercase',letterSpacing:'.04em',color:C.muted}}>Segments</h3><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{TAGS.map(t=><div key={t.id} onClick={()=>{setTab('contacts');setContactFilter(t.id)}} style={{cursor:'pointer',display:'flex',alignItems:'center',gap:8,padding:'8px 14px',borderRadius:10,background:t.bg,border:`1px solid ${t.color}18`}}><span style={{fontSize:16}}>{t.icon}</span><span style={{fontSize:13,fontWeight:600,color:t.color}}>{t.label}</span><span style={{fontSize:20,fontWeight:800,color:t.color,fontFamily:"'Cormorant Garamond',Georgia,serif"}}>{ct(t.id)}</span></div>)}</div></Card>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}>
        <Card><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><h3 style={{fontSize:13,fontWeight:700,margin:0}}>Derniers contacts</h3><Btn sm v="soft" onClick={()=>setTab('contacts')}>Voir tout</Btn></div>{!contacts.length&&<p style={{color:C.muted,fontSize:13}}>Aucun</p>}{contacts.slice(0,5).map(c=><div key={c.id} onClick={()=>setShowDetail(c)} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'7px 0',borderBottom:`1px solid ${C.borderLight}`,cursor:'pointer'}}><div><div style={{fontWeight:600,fontSize:13}}>{c.name}</div><div style={{fontSize:10,color:C.muted}}>{c.email}</div></div><div style={{display:'flex',gap:3}}>{c.tags.slice(0,2).map(t=><CTag key={t} tagId={t} small/>)}</div></div>)}</Card>
        <Card><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><h3 style={{fontSize:13,fontWeight:700,margin:0}}>Activité</h3>{ghOk&&<Btn sm v="soft" onClick={doGH} disabled={ghLoading}><Ico d={IC.refresh} size={12}/></Btn>}</div>{[...activity.slice(0,3).map(a=>({type:'log',msg:a.msg,date:a.time?.slice(0,10)})),...ghCommits.slice(0,3).map(c=>({type:'commit',msg:c.message,date:c.date,author:c.author,sha:c.sha,url:c.url}))].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,6).map((item,i)=><div key={i} style={{padding:'6px 0',borderBottom:`1px solid ${C.borderLight}`,display:'flex',gap:8}}><span style={{color:item.type==='commit'?C.sky:C.green,marginTop:2}}><Ico d={item.type==='commit'?IC.git:IC.zap} size={12}/></span><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,fontWeight:500,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{item.type==='commit'?<a href={item.url} target="_blank" rel="noopener" style={{color:C.navy,textDecoration:'none'}}>{item.msg}</a>:item.msg}</div><div style={{fontSize:10,color:C.muted}}>{item.date}{item.author?` · ${item.author}`:''}{item.sha?` · ${item.sha}`:''}</div></div></div>)}{!activity.length&&!ghCommits.length&&<p style={{color:C.muted,fontSize:12}}>—</p>}</Card>
      </div>
      <Card style={{marginTop:14}}><h3 style={{fontSize:13,fontWeight:700,margin:'0 0 10px',textTransform:'uppercase',letterSpacing:'.04em',color:C.muted}}>Automations actives</h3><div style={{display:'flex',flexWrap:'wrap',gap:6}}>{automations.filter(a=>a.active).map(a=><span key={a.id} style={{padding:'5px 12px',borderRadius:8,fontSize:11,fontWeight:600,background:C.greenFade,color:C.green,display:'flex',alignItems:'center',gap:5}}><Ico d={IC.zap} size={11}/>{a.name}<span style={{opacity:.5}}>({a.channel})</span></span>)}</div></Card>
    </>}

    {/* CONTACTS */}
    {tab==='contacts'&&<>
      <STitle icon={IC.users} right={<div style={{display:'flex',gap:6,flexWrap:'wrap'}}><Btn sm v="ghost" onClick={()=>setShowImport(true)}><Ico d={IC.upload} size={13}/> CSV</Btn><Btn sm v="ghost" onClick={()=>exportCSV(filt)}><Ico d={IC.download} size={13}/> Export</Btn>{haOk&&<Btn sm v="ochre" onClick={syncHA} disabled={haLoading}>{haLoading?'…':'🫶 HelloAsso'}</Btn>}<Btn sm onClick={()=>setShowAdd(true)}><Ico d={IC.plus} size={13}/> Contact</Btn></div>}>Contacts <span style={{fontWeight:400,color:C.muted}}>({contacts.length})</span></STitle>
      <div style={{display:'flex',gap:2,marginBottom:16,borderBottom:`1px solid ${C.border}`}}>{[{id:'list',l:'Liste',ic:IC.users},{id:'automations',l:'Automations',ic:IC.zap},{id:'campaigns',l:'Campagnes',ic:IC.send}].map(t=><button key={t.id} onClick={()=>setContactTab(t.id)} style={{padding:'9px 16px',border:'none',background:'none',cursor:'pointer',fontFamily:'inherit',fontSize:12,fontWeight:600,display:'flex',alignItems:'center',gap:5,color:contactTab===t.id?C.navy:C.muted,borderBottom:contactTab===t.id?`2px solid ${C.sky}`:'2px solid transparent'}}><Ico d={t.ic} size={13}/>{t.l}</button>)}</div>

      {contactTab==='list'&&<><div style={{display:'flex',gap:8,marginBottom:16,flexWrap:'wrap',alignItems:'center'}}><div style={{position:'relative',flex:'1 1 200px',maxWidth:280}}><span style={{position:'absolute',left:10,top:'50%',transform:'translateY(-50%)',color:C.muted}}><Ico d={IC.search}/></span><input value={contactSearch} onChange={e=>setContactSearch(e.target.value)} placeholder="Rechercher…" style={{...iStyle,paddingLeft:34}}/></div><div style={{display:'flex',gap:4,flexWrap:'wrap'}}><button onClick={()=>setContactFilter('all')} style={{padding:'4px 10px',borderRadius:8,border:`1px solid ${contactFilter==='all'?C.sky:C.border}`,background:contactFilter==='all'?C.skyFade:'transparent',color:contactFilter==='all'?C.sky:C.muted,fontSize:11,fontWeight:600,cursor:'pointer',fontFamily:'inherit'}}>Tous ({contacts.length})</button>{TAGS.map(t=><button key={t.id} onClick={()=>setContactFilter(t.id)} style={{padding:'4px 10px',borderRadius:8,border:`1px solid ${contactFilter===t.id?t.color:C.border}`,background:contactFilter===t.id?t.bg:'transparent',color:contactFilter===t.id?t.color:C.muted,fontSize:11,fontWeight:600,cursor:'pointer',fontFamily:'inherit'}}>{t.icon} {ct(t.id)}</button>)}</div></div>
      <div style={{overflowX:'auto',borderRadius:12,border:`1px solid ${C.border}`,background:C.white}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr style={{background:C.bg}}>{['Nom','Email','Tags','Source','Date',''].map((h,i)=><th key={i} style={{padding:'11px 14px',textAlign:'left',fontWeight:700,color:C.navy,fontSize:10,textTransform:'uppercase',letterSpacing:'.06em',borderBottom:`1px solid ${C.border}`}}>{h}</th>)}</tr></thead><tbody>{filt.map(c=><tr key={c.id} onClick={()=>setShowDetail(c)} style={{cursor:'pointer'}}><Td style={{fontWeight:600}}>{c.name}</Td><Td style={{color:C.muted}}>{c.email}</Td><Td><div style={{display:'flex',gap:3,flexWrap:'wrap'}}>{c.tags.map(t=><CTag key={t} tagId={t}/>)}</div></Td><Td style={{fontSize:11,color:C.muted}}>{c.source}</Td><Td style={{fontSize:11,color:C.muted}}>{c.date}</Td><Td><div style={{display:'flex',gap:3}} onClick={e=>e.stopPropagation()}>{!c.tags.includes('newsletter')&&<Btn sm v="sky" onClick={()=>toggleTag(c.id,'newsletter')} style={{fontSize:10,padding:'2px 6px'}}>+NL</Btn>}{!c.tags.includes('membre')&&<Btn sm v="green" onClick={()=>toggleTag(c.id,'membre')} style={{fontSize:10,padding:'2px 6px'}}>+Mb</Btn>}<Btn sm v="ghost" onClick={()=>delContact(c.id)} style={{padding:'2px 6px'}}><Ico d={IC.trash} size={12}/></Btn></div></Td></tr>)}{!filt.length&&<tr><td colSpan={6} style={{padding:32,textAlign:'center',color:C.muted}}>Aucun contact</td></tr>}</tbody></table></div></>}

      {contactTab==='automations'&&<div style={{display:'grid',gap:10}}>{automations.map(a=><Card key={a.id} padding="16px 20px" style={{display:'flex',justifyContent:'space-between',alignItems:'center',opacity:a.active?1:.55}}><div><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:4}}><Ico d={IC.zap} size={14} color={a.active?C.green:C.muted}/><span style={{fontWeight:700,fontSize:14}}>{a.name}</span><Badge s={a.channel.includes('email')?'ready':'ok'} label={a.channel}/></div><div style={{fontSize:12,color:C.muted}}><b style={{color:C.navy}}>Trigger:</b> {a.trigger}</div><div style={{fontSize:11,color:C.mutedLight,marginTop:2}}>{a.desc}</div></div><div onClick={()=>setAutomations(p=>p.map(x=>x.id===a.id?{...x,active:!x.active}:x))} style={{width:44,height:24,borderRadius:12,background:a.active?C.green:C.border,cursor:'pointer',position:'relative',flexShrink:0}}><div style={{width:20,height:20,borderRadius:10,background:C.white,position:'absolute',top:2,left:a.active?22:2,transition:'left .2s',boxShadow:'0 1px 4px rgba(0,0,0,.15)'}}/></div></Card>)}</div>}

      {contactTab==='campaigns'&&<><Card style={{marginBottom:14}}><h3 style={{fontSize:15,fontWeight:700,margin:'0 0 14px',fontFamily:"'Cormorant Garamond',Georgia,serif"}}>Campagne</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginBottom:12}}><Field label="Canal"><select value={campaign.channel} onChange={e=>setCampaign({...campaign,channel:e.target.value})} style={iStyle}><option value="email">Email (Brevo)</option><option value="telegram">Telegram</option></select></Field><Field label="Segment"><select value={campaign.targetTag} onChange={e=>setCampaign({...campaign,targetTag:e.target.value})} style={iStyle}>{TAGS.map(t=><option key={t.id} value={t.id}>{t.icon} {t.label} ({ct(t.id)})</option>)}</select></Field></div>{campaign.channel==='email'&&<Field label="Objet"><input value={campaign.subject} onChange={e=>setCampaign({...campaign,subject:e.target.value})} placeholder="Objet" style={iStyle}/></Field>}<Field label="Message"><textarea value={campaign.body} onChange={e=>setCampaign({...campaign,body:e.target.value})} rows={6} placeholder="Message…" style={{...iStyle,resize:'vertical',lineHeight:1.5}}/></Field><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:4}}><span style={{fontSize:12,color:C.muted}}>{contacts.filter(c=>c.tags.includes(campaign.targetTag)&&c.email).length} dest.</span><Btn onClick={doSend}><Ico d={IC.send} size={14}/> Envoyer</Btn></div></Card>
      <Card><h4 style={{fontSize:12,fontWeight:700,margin:'0 0 10px',textTransform:'uppercase',color:C.muted}}>Templates</h4><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}>{TPL.map((t,i)=><button key={i} onClick={()=>setCampaign({...campaign,body:t.body,subject:t.subject||''})} style={{padding:'10px 14px',borderRadius:10,border:`1px solid ${C.border}`,background:'transparent',cursor:'pointer',textAlign:'left',fontFamily:'inherit'}}><div style={{fontSize:13,fontWeight:600,marginBottom:3}}>{t.label}</div><div style={{fontSize:11,color:C.muted,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{t.body.slice(0,50)}…</div></button>)}</div></Card></>}

      <Modal open={!!showDetail} onClose={()=>setShowDetail(null)} title={showDetail?.name||''}>{showDetail&&<><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginBottom:16}}><div><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:'uppercase',marginBottom:2}}>Email</div>{showDetail.email}</div><div><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:'uppercase',marginBottom:2}}>Source</div>{showDetail.source}</div><div><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:'uppercase',marginBottom:2}}>Date</div>{showDetail.date}</div>{showDetail.amount&&<div><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:'uppercase',marginBottom:2}}>Montant</div>{showDetail.amount}€</div>}</div><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:'uppercase',marginBottom:6}}>Tags</div><div style={{display:'flex',flexWrap:'wrap',gap:4,marginBottom:16}}>{TAGS.map(t=><button key={t.id} onClick={()=>{toggleTag(showDetail.id,t.id);setShowDetail({...showDetail,tags:showDetail.tags.includes(t.id)?showDetail.tags.filter(x=>x!==t.id):[...showDetail.tags,t.id]})}} style={{padding:'5px 12px',borderRadius:8,fontSize:12,fontWeight:600,cursor:'pointer',fontFamily:'inherit',border:`1px solid ${showDetail.tags.includes(t.id)?t.color:C.border}`,background:showDetail.tags.includes(t.id)?t.bg:'transparent',color:showDetail.tags.includes(t.id)?t.color:C.muted}}>{t.icon} {t.label}</button>)}</div><div style={{display:'flex',gap:8,justifyContent:'flex-end'}}><Btn v="danger" sm onClick={()=>{delContact(showDetail.id);setShowDetail(null)}}><Ico d={IC.trash} size={12}/> Supprimer</Btn><Btn v="ghost" onClick={()=>setShowDetail(null)}>Fermer</Btn></div></>}</Modal>
      <Modal open={showAdd} onClose={()=>setShowAdd(false)} title="Nouveau contact"><Field label="Nom"><input value={newC.name} onChange={e=>setNewC({...newC,name:e.target.value})} placeholder="Nom" style={iStyle}/></Field><Field label="Email"><input type="email" value={newC.email} onChange={e=>setNewC({...newC,email:e.target.value})} placeholder="email@…" style={iStyle}/></Field><Field label="Tags"><div style={{display:'flex',flexWrap:'wrap',gap:4}}>{TAGS.map(t=><button key={t.id} onClick={()=>setNewC({...newC,tags:newC.tags.includes(t.id)?newC.tags.filter(x=>x!==t.id):[...newC.tags,t.id]})} style={{padding:'4px 10px',borderRadius:8,fontSize:11,fontWeight:600,cursor:'pointer',fontFamily:'inherit',border:`1px solid ${newC.tags.includes(t.id)?t.color:C.border}`,background:newC.tags.includes(t.id)?t.bg:'transparent',color:newC.tags.includes(t.id)?t.color:C.muted}}>{t.icon} {t.label}</button>)}</div></Field><div style={{display:'flex',gap:8,justifyContent:'flex-end',marginTop:18}}><Btn v="ghost" onClick={()=>setShowAdd(false)}>Annuler</Btn><Btn onClick={addContact}>Ajouter</Btn></div></Modal>
      <Modal open={showImport} onClose={()=>setShowImport(false)} title="Importer CSV" wide><p style={{fontSize:12,color:C.muted,margin:'0 0 10px'}}>Colonnes : <code style={{background:C.bgAlt,padding:'1px 6px',borderRadius:4,fontSize:11}}>nom, email, tags</code></p><textarea value={importText} onChange={e=>setImportText(e.target.value)} rows={8} placeholder="nom;email;tags" style={{...iStyle,fontFamily:'monospace',fontSize:11,resize:'vertical'}}/><div style={{display:'flex',gap:8,justifyContent:'flex-end',marginTop:12}}><Btn v="ghost" onClick={()=>setShowImport(false)}>Annuler</Btn><Btn onClick={doImport}><Ico d={IC.upload} size={13}/> Importer</Btn></div></Modal>
    </>}

    {/* ARTICLES */}
    {tab==='articles'&&<><STitle icon={IC.file} sub={notionOk?'Synchronisé avec Notion':'Connectez Notion dans Config'} right={notionOk&&<div style={{display:'flex',gap:6}}><Btn sm v="sky" onClick={doNotion} disabled={notionLoading}><Ico d={IC.refresh} size={13}/> {notionLoading?'…':'Sync'}</Btn><Btn sm v="ghost" onClick={()=>window.open(`https://notion.so/${config.notionDbId.replace(/-/g,'')}`, '_blank')}><Ico d={IC.ext} size={13}/> Notion</Btn></div>}>Articles</STitle>
      {!notionOk?<Card style={{textAlign:'center',padding:'48px 24px'}}><div style={{fontSize:40,marginBottom:12}}>📝</div><h3 style={{margin:'0 0 8px',fontFamily:"'Cormorant Garamond',Georgia,serif",fontSize:20}}>Articles gérés dans Notion</h3><p style={{color:C.muted,fontSize:13,margin:'0 0 20px',maxWidth:420,marginLeft:'auto',marginRight:'auto',lineHeight:1.5}}>L'équipe rédige dans Notion. Le dashboard synchronise l'état.</p><Btn onClick={()=>setTab('config')}>Configurer Notion</Btn></Card>
      :<>{notionError&&<div style={{background:C.redBg,borderRadius:10,padding:'10px 16px',marginBottom:14,fontSize:13,color:C.red}}>{notionError}</div>}{notionArticles.length>0?<div style={{overflowX:'auto',borderRadius:12,border:`1px solid ${C.border}`,background:C.white}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr style={{background:C.bg}}>{['Titre','Auteur','Pôle','Statut',''].map((h,i)=><th key={i} style={{padding:'11px 14px',textAlign:'left',fontWeight:700,color:C.navy,fontSize:10,textTransform:'uppercase',letterSpacing:'.06em',borderBottom:`1px solid ${C.border}`}}>{h}</th>)}</tr></thead><tbody>{notionArticles.map((a,i)=><tr key={a.id||i}><Td style={{fontWeight:600}}>{a.title}</Td><Td>{a.author||'—'}</Td><Td>{a.pole?<Badge s="ok" label={a.pole} color={C.navy} bg={C.tNavy}/>:'—'}</Td><Td><Badge s={a.status||'draft'}/></Td><Td>{a.notionUrl&&<a href={a.notionUrl} target="_blank" rel="noopener" style={{color:C.muted}}><Ico d={IC.ext} size={13}/></a>}</Td></tr>)}</tbody></table></div>:!notionLoading&&<Card style={{textAlign:'center',padding:32}}><p style={{color:C.muted,fontSize:13,margin:0}}>Cliquez « Sync »</p></Card>}
      <Card style={{marginTop:14}} padding="14px 20px"><div style={{fontSize:12,color:C.muted,lineHeight:1.6}}><b style={{color:C.navy}}>Workflow :</b> Rédiger Notion → "Prêt" → Sync → HTML + commit GitHub → Site à jour</div></Card></>}
    </>}

    {/* SITE */}
    {tab==='site'&&<><STitle icon={IC.globe} right={<Btn v={linkChecking?'ghost':'primary'} sm onClick={doLinks} disabled={linkChecking}><Ico d={linkChecking?IC.refresh:IC.play} size={13}/> {linkChecking?'…':'Vérifier'}</Btn>}>Site & Monitoring</STitle>
      <div style={{display:'flex',gap:12,marginBottom:20}}><Metric icon={IC.globe} label="Pages" val={PAGES.length} color={C.navy}/><Metric icon={IC.check} label="OK" val={okP} color={C.green}/><Metric icon={IC.alert} label="Erreurs" val={errP} color={errP?C.red:C.muted}/></div>
      {Object.entries(pGroups).map(([g,pages])=><div key={g} style={{marginBottom:16}}><h3 style={{fontSize:11,fontWeight:700,textTransform:'uppercase',letterSpacing:'.06em',color:C.muted,margin:'0 0 8px'}}>{g}</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill, minmax(240px, 1fr))',gap:8}}>{pages.map((p,i)=>{const r=linkResults.find(lr=>lr.path===p.path)||{};return<a key={i} href={`${SITE}${p.path}`} target="_blank" rel="noopener" style={{background:C.white,borderRadius:10,padding:'12px 16px',border:`1px solid ${r.status==='error'?C.red+'40':C.border}`,display:'flex',justifyContent:'space-between',alignItems:'center',textDecoration:'none',color:C.navy}}><div><div style={{fontWeight:600,fontSize:13}}>{p.name}</div><div style={{fontSize:10,color:C.muted,fontFamily:'monospace'}}>{p.path}</div></div><div style={{display:'flex',alignItems:'center',gap:6}}>{r.time&&<span style={{fontSize:10,color:C.muted}}>{r.time}ms</span>}<Badge s={r.status||'unchecked'}/></div></a>})}</div></div>)}
    </>}

    {/* CONFIG */}
    {tab==='config'&&<><STitle icon={IC.settings}>Configuration</STitle>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}>
        <Card><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:14}}><span style={{fontSize:18}}>🫶</span><h3 style={{margin:0,fontSize:15,fontWeight:700}}>HelloAsso</h3><Dot ok={haOk} label={haOk?'OK':''}/></div><Field label="Client ID" help="HelloAsso → Mon compte → API"><input value={config.helloassoClientId} onChange={e=>setConfig({...config,helloassoClientId:e.target.value})} style={iStyle}/></Field><Field label="Client Secret"><input type="password" value={config.helloassoClientSecret} onChange={e=>setConfig({...config,helloassoClientSecret:e.target.value})} style={iStyle}/></Field><Field label="Slug" help="helloasso.com/associations/[slug]"><input value={config.helloassoOrg} onChange={e=>setConfig({...config,helloassoOrg:e.target.value})} placeholder="institut-rousseau" style={iStyle}/></Field></Card>
        <Card><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:14}}><span style={{fontSize:18}}>📬</span><h3 style={{margin:0,fontSize:15,fontWeight:700}}>Brevo</h3><Dot ok={brevoOk} label={brevoOk?'OK':''}/></div><Field label="Clé API" help="Brevo → Paramètres → Clés API"><input type="password" value={config.brevoKey} onChange={e=>setConfig({...config,brevoKey:e.target.value})} placeholder="xkeysib-…" style={iStyle}/></Field></Card>
        <Card><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:14}}><span style={{fontSize:18}}>✈️</span><h3 style={{margin:0,fontSize:15,fontWeight:700}}>Telegram</h3><Dot ok={tgOk} label={tgOk?'OK':''}/></div><Field label="Bot Token" help="@BotFather"><input type="password" value={config.telegramBotToken} onChange={e=>setConfig({...config,telegramBotToken:e.target.value})} style={iStyle}/></Field><Field label="Chat ID"><input value={config.telegramChatId} onChange={e=>setConfig({...config,telegramChatId:e.target.value})} placeholder="-100…" style={iStyle}/></Field>{tgOk&&<Btn sm v="sky" onClick={()=>sendTelegramMessage(config.telegramBotToken,config.telegramChatId,'🔔 Test IR').then(()=>notify('OK')).catch(e=>notify(e.message,true))} style={{marginTop:4}}>Test</Btn>}</Card>
        <Card><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:14}}><span style={{fontSize:18}}>📝</span><h3 style={{margin:0,fontSize:15,fontWeight:700}}>Notion</h3><Dot ok={notionOk} label={notionOk?'OK':''}/></div><Field label="Clé API" help="notion.so/my-integrations"><input type="password" value={config.notionKey} onChange={e=>setConfig({...config,notionKey:e.target.value})} placeholder="ntn_…" style={iStyle}/></Field><Field label="Database ID"><input value={config.notionDbId} onChange={e=>setConfig({...config,notionDbId:e.target.value})} style={iStyle}/></Field><div style={{fontSize:11,color:C.muted,background:C.bgAlt,padding:'8px 10px',borderRadius:8,fontFamily:'monospace',lineHeight:1.8,marginTop:6}}>Titre · Auteur · Statut · Date · Pôle</div></Card>
        <Card><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:14}}><Ico d={IC.git} size={18}/><h3 style={{margin:0,fontSize:15,fontWeight:700}}>GitHub</h3><Dot ok={ghOk} label={ghOk?'OK':''}/></div><Field label="Owner"><input value={config.ghOwner} onChange={e=>setConfig({...config,ghOwner:e.target.value})} style={iStyle}/></Field><Field label="Repo"><input value={config.ghRepo} onChange={e=>setConfig({...config,ghRepo:e.target.value})} style={iStyle}/></Field><Field label="Token" help="Optionnel (repos publics)"><input type="password" value={config.ghToken} onChange={e=>setConfig({...config,ghToken:e.target.value})} style={iStyle}/></Field></Card>
        <Card><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:14}}><Ico d={IC.globe} size={18} color={C.sky}/><h3 style={{margin:0,fontSize:15,fontWeight:700}}>Site</h3></div><Field label="URL"><div style={{...iStyle,background:C.bgAlt,color:C.muted}}>{SITE}</div></Field><p style={{fontSize:11,color:C.mutedLight,margin:'6px 0 0'}}>Modifier dans <code style={{background:C.bgAlt,padding:'0 4px',borderRadius:3}}>src/App.jsx</code> après migration.</p></Card>
      </div>
      <div style={{marginTop:18,display:'flex',justifyContent:'flex-end'}}><Btn onClick={()=>saveCfg(config)}><Ico d={IC.save} size={14}/> Sauvegarder</Btn></div>
    </>}

    </main>
    <style>{`*{box-sizing:border-box}body{margin:0}@keyframes slideIn{from{transform:translateY(-10px);opacity:0}to{transform:translateY(0);opacity:1}}button:hover:not(:disabled){filter:brightness(1.06)}button:active:not(:disabled){transform:scale(.98)}tr:hover{background:${C.bg}88!important}input:focus,select:focus,textarea:focus{border-color:${C.sky}!important;box-shadow:0 0 0 3px ${C.skyFade}!important}a:hover{opacity:.85}::-webkit-scrollbar{width:6px;height:6px}::-webkit-scrollbar-thumb{background:${C.border};border-radius:3px}@media(max-width:768px){main{padding:14px 12px!important}header,nav{padding:0 14px!important}div[style*="grid-template-columns: 1fr 1fr"]{grid-template-columns:1fr!important}div[style*="grid-template-columns: repeat"]{grid-template-columns:1fr!important}}`}</style>
  </div>)
}
